### ISSUE TITLE
Rectified data have changed _Fillvalue and precision

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/esgfpub#37]
Looking at the original version and truncated version: 
/p/user_pub/e3sm/warehouse/E3SM/1_1/piControl/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0/20181217.CNTL_CNPCTC1850_OIBGC.ne30_oECv3.edison.cam.h1.1919-01-01-00000.nc

/v0.2/20181217.CNTL_CNPCTC1850_OIBGC.ne30_oECv3.edison.cam.h1.1919-01-01-00000.trunc.nc

In the original .nc files, there was no _Fillvalue attribute, but processed data have additional _Fillvalue attribute added, and fill_value changed from 1e+20 to 9.96921e+36.

**Comment by sterlingbaldwin** [comment]
ah ok ya, this is the default behavior of xarray. I'll change it to use the correct fill value.

**Comment by tomvothecoder** [comment]
> In the original .nc files, there was no _Fillvalue attribute, but processed data have additional _Fillvalue attribute added, and fill_value changed from 1e+20 to 9.96921e+36.

> "For the missing values, in all NetCDF files, they are prescribed as 9.9691e+36. However, when I used "ncdump -h" to check the information of each file. They are defined as 1.e+20. There is inconsistency between the defined missing value and that prescribed in the .nc file. Furthermore, I noticed that the missing values shown in the NetCDF files range from 1e+36 to 9.9691e+36. These values are all missing values, but their values are inconsistent."

@chengzhuzhang @TonyB9000 -- Hey Jill, I'm confused between your description and the user's description of the issue because they are opposite. Is the default missing value 9.96921e+36, but it is changing to 1e+20 after running `esgfpub`?

Here's my walk through to figure out if this issue is resolved:

## 1. Find code references to `_FillValue`:
https://github.com/E3SM-Project/esgfpub/blob/76ccbc7b9cf9661e9de2bb99b75a33588bcffb6d/esgfpub/esgfpub/scripts/timerect/timeindexchecker.py#L84-L105

https://github.com/E3SM-Project/esgfpub/blob/76ccbc7b9cf9661e9de2bb99b75a33588bcffb6d/esgfpub/esgfpub/scripts/timerect/timerectifier.py#L157-L171

According to the above functions, the `_FillValue` is set using the matching key value in the `netCDF4.default_fillvals` dictionary (below).

```
# https://github.com/Unidata/netcdf4-python/blob/f8a245f0c9690dbdef170f3241c6b48ee23a1102/src/netCDF4/_netCDF4.pyx#L1372-L1384
# default fill_value to numpy datatype mapping.
default_fillvals = {#'S1':NC_FILL_CHAR,
                     'S1':'\0',
                     'i1':NC_FILL_BYTE,
                     'u1':NC_FILL_UBYTE,
                     'i2':NC_FILL_SHORT,
                     'u2':NC_FILL_USHORT,
                     'i4':NC_FILL_INT,
                     'u4':NC_FILL_UINT,
                     'i8':NC_FILL_INT64,
                     'u8':NC_FILL_UINT64,
                     'f4':NC_FILL_FLOAT,
                     'f8':NC_FILL_DOUBLE}
```

Documentation on the `NC_FILL` values:
https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_8h.html#a2b5dac7ffdb432566f72bab96ecb5c0d
- 9.96921e+36 is the equivalent fill value for [NC_FILL_DOUBLE](https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_8h.html#aecf292ddebb9cd5178d69d3374eb4f2a).

---
https://github.com/E3SM-Project/esgfpub/blob/76ccbc7b9cf9661e9de2bb99b75a33588bcffb6d/warehouse/warehouse/scripts/rectify_time_index.py#L362-L373

This sets `ds[variable].encoding['_FillValue'] = False`, which turns off filling.

## 2. Check file Git histories for references in commits/PRs
I checked the git history of the above files and found a merged PR that might be related to this #56 

## 3. Findings and summary
- I don't see 1e20 being set anywhere, and that is not the default xarray fill value.
  -  ["By default, variables with float types are attributed a _FillValue of NaN in the output file, unless explicitly disabled with an encoding {'_FillValue': None}."](https://xarray.pydata.org/en/stable/user-guide/io.html#scaling-and-type-conversions)
- PR #56 seems to be related to this issue. I think this is good example of why connecting issues to PRs is important for an up to date track record!

**Based on my findings, I think this issue might have been addressed in PR #56.**

## 4. References
- Xarray documentation on `_FillValue`: https://xarray.pydata.org/en/stable/user-guide/io.html#scaling-and-type-conversions
- Related issue that was addressed awhile ago on the xarray repo: https://github.com/pydata/xarray/issues/1163

**Comment by TonyB9000** [comment]
Hi Tom,

I do recall this general “fill_value” issue being fixed (in the codes) over a year ago, although there may be “unfixed-published” datasets out there.

Aside:  NO variables remain that are published with double-precision, so the application of a double-precision fill-value would be an issue – but I don’t see that here (mantissa too small).

____tony____

**Comment by tomvothecoder** [comment]
> @chengzhuzhang @TonyB9000 -- Hey Jill, I'm confused between your description and the user's description of the issue because they are opposite. Is the default missing value 9.96921e+36, but it is changing to 1e+20 after running esgfpub?

Jay clarified in his email that the default missing value for `_FillValue` should be 1e+20, but it is changing to a value in the range of 1e+36 through 9.969e+36. This description aligns with Jill's description for this issue.

We might want to validate that this issue is actually fixed by running `esgfpub` on a file that has a `_FillValue` = 1e+20 and making sure it doesn't change to 1e+36 or 9.969e+36.

**Comment by TonyB9000** [comment]
Hi Tom,
            “Is the default missing value 9.96921e+36, but it is changing to 1e+20 after running esgfpub?”

That should be impossible.  The esgfpub process does not touch the files, does not move, or even read them.  It publishes the data that is collected in the mapfile that is generated prior to publication.

Mapfile generation reads each file of a dataset, generated an sha256 hash of the file, and other information.  A typical line from a mapfile looks like this:

CMIP6.CMIP.E3SM-Project.E3SM-1-1.historical.r1i1p1f1.Amon.wap.gr#20211213 | /p/user_pub/work/CMIP6/CMIP/E3SM-Project/E3SM-1-1/historical/r1i1p1f1/Amon/wap/gr/v20211213/wap_Amon_E3SM-1-1_historical_r1i1p1f1_gr_200001-201412.nc | 781429895 | mod_time=1628060626.3198276 | checksum=7c67c756847c99943fd98e22529a1d1d2bb43f245026501fd0a976e3124fc0ca | checksum_type=SHA256

(format):  ~dataset_id | pub_path_to_file | file_size | file_mod_time[in epoch seconds] | hash_value | hash_type

The esgfpub process only reads that mapfile and pushes the data to a search database and web-server, whose URLs are crafted from the “pub_path_to_file”.

The only “candidate” processes that would change the data-values of a file are:

            data_type        process
            = = = = = =        = = = = = =
            native              Validation        (can edit the time-index, join overlapping files from restarts)
            derivatives      PostProcess     (ncclimo – pulls per-variable data from native files into climo or time-series collections – should not change data)
            derivatives      Cmorizing        (conversion of E3SM timeseries to CMIP6 timeseries format – possible change of data could occur?)
            ANY                 Custom            (one-off “fixes” have occurred, like converting MPAS double-precision to single-precision, and
                                                            supplying a fill_value where a newer compiler generated “0” I think)



____tony____
