### ISSUE TITLE
Issues with timechecker.py reporting

### ISSUE THREAD

**Issue by TonyB9000** [E3SM-Project/esgfpub#8]
In applying timechecker.py to a (potentially large) list of input dataset directories (sequenced by a controlling batch script), the outputs from timechecker (stdout, stderr, return code) do not easily lend themselves to automated distinction between "good" (Pass) or "bad" (Fail) for the given datasets.  In particular, it appears that both good and bad datasets result in the same (0) exit code, and messages written to stdout appear sometimes just informative, other times an indication of error, and it is not explicit which is which.

Also, the verbose output describing bad datasets, while valuable for the operator, are only attributable to a specific dataset in post-hoc processing (seeking the dataset path in stdout messaging, the absence of which is the only clue to a "good" dataset.)

Lastly, for batch and background processing, a "-q, --quiet" mode that turns off the "status-bar" terminal I/O would be nice.

Suggestions:

1. Return sys.exit(0) for a Pass dataset, and some other value for a Fail dataset
2. Supply at least one line to stdout that is strictly "Pass:<dataset ID/path>" or "Fail:<dataset ID/path>", preceded by a timestamp.
3. Ideally, open a file named by the dataset ("timechecker_issues-<datasetID>") in which to place verbose findings.  This would facilitate post processing, especially when a large batch of datasets are being processed.  Also, if certain types of errors suggest certain types of rectification processing, introduce a vocabulary (code word) that can identify and distinguish these for possible automated post-processing.
4. (optional): add the "--quiet' option to suppress the active status-bar for batch/background processing.

**Comment by TonyB9000** [comment]
I'd be happy to try my hand at some of this - assuming I can gel with the coding style.

**Comment by TonyB9000** [comment]
I guess "close with comment" does not mean what I think it means... ;)

**Comment by sterlingbaldwin** [comment]
Originally, I used the exit code to denote if there had been a fairlure, i.e. an exception had been thrown, but it would be totally reasonable to make the exit code return the status of if there was a time issue or not.

**Comment by TonyB9000** [comment]
OK, that is going to be my main goal. (since a controlling batch process or “parent” would get immediate feedback for decision-making).

Question:

            if calendar not in calendars:
                raise ValueError(f"Unsupported calendar type {calendar}")

Is that intended to cause an abort?  It appears to continue processing – ok I guess.

Does every issue in “issues” (Empty time-index, start index is off …) imply “bad dataset”?

Thanks!  ____tony____

**Comment by sterlingbaldwin** [comment]
Right now there's just that one calendar. To the best of my knowledge, the model only gets run with this calendar, but its possible to use other ones, so I wanted to make it easy to add more if we need to.

Any issues implies that there was a problem with the time index.

**Comment by TonyB9000** [comment]
OK, just to be clear:

        if not start:
            raise ValueError(f"The year stamp search pattern {pattern} didnt find what it was expecting")

This is not technically an “issue”, as it was not added to the “issues” list.  So this Does_Not/Does represent a bad dataset (or aborted processing at least)?

**Comment by sterlingbaldwin** [comment]
It represents a situation that the code cant handle without being updated. This shouldnt happen with any of the datasets we've handled so far, but who knows about what datasets we'll get in the future.

**Comment by TonyB9000** [comment]
OK, I’ve made and tested the changes.  I decided to forego the “separate error file per dataset” for the time being.  Everything else looks good (need to find a “happy” dataset to be sure.)

The “-q, --quiet” suppresses the status bar by adding “disable=True” (aka, args.quiet) to the tqdm parameters.

Here is the output (stdout) from the two files I’ve tested:

20210105.153716:Running timechecker:dataset=/p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BCRC/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0
20210105_153718:Found sub-monthly data
20210105_153718:Time frequency detected as 1.0 days since 1850-01-01 00:00:00
20210105_153723:Empty time index found in /p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BCRC/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0/20191207.BCRC_CNPECACNT_SSP585.ne30_oECv3.cori-knl.cam.h1.2101-01-02-00000.nc
20210105_153723:Result=Fail:dataset=/p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BCRC/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0
20210105.153723:Running timechecker:dataset=/p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BDRD/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0
20210105_153725:Found sub-monthly data
20210105_153725:Time frequency detected as 1.0 days since 1850-01-01 00:00:00
20210105_153729:Empty time index found in /p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BDRD/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0/20191108.BDRD_CNPECACNT_SSP585.ne30_oECv3.cori-knl.cam.h1.2076-01-02-00000.nc
20210105_153729:index issue file: /p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BDRD/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0/20200326.BDRD_CNPECACNT_SSP585.ne30_oECv3.cori-knl.cam.h1.2077-01-02-00000.nc has index (82856.0, 83220.0) should be ((82492.0, 83220.0)), the start index is off by (364.0) days.
20210105_153729:Empty time index found in /p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BDRD/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0/20200326.BDRD_CNPECACNT_SSP585.ne30_oECv3.cori-knl.cam.h1.2101-01-02-00000.nc
20210105_153729:Result=Fail:dataset=/p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BDRD/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0

Presently, my controlling batch script “validation.sh” poses as “Validation” and will soon take care of updating the dataset status files.

I intend to run it on a “Pile O’ Datasets” soon.

**Comment by sterlingbaldwin** [comment]
For testing, I usually use one of our already published known good datasets to make sure there aren’t any false positives.

</Sterling Baldwin>

On Jan 5, 2021, at 3:48 PM, TonyB9000 <notifications@github.com> wrote:

﻿

OK, I’ve made and tested the changes. I decided to forego the “separate error file per dataset” for the time being. Everything else looks good (need to find a “happy” dataset to be sure.)

The “-q, --quiet” suppresses the status bar by adding “disable=True” (aka, args.quiet) to the tqdm parameters.

Here is the output (stdout) from the two files I’ve tested:

20210105.153716:Running timechecker:dataset=/p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BCRC/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0
20210105_153718:Found sub-monthly data
20210105_153718:Time frequency detected as 1.0 days since 1850-01-01 00:00:00
20210105_153723:Empty time index found in /p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BCRC/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0/20191207.BCRC_CNPECACNT_SSP585.ne30_oECv3.cori-knl.cam.h1.2101-01-02-00000.nc
20210105_153723:Result=Fail:dataset=/p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BCRC/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0
20210105.153723:Running timechecker:dataset=/p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BDRD/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0
20210105_153725:Found sub-monthly data
20210105_153725:Time frequency detected as 1.0 days since 1850-01-01 00:00:00
20210105_153729:Empty time index found in /p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BDRD/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0/20191108.BDRD_CNPECACNT_SSP585.ne30_oECv3.cori-knl.cam.h1.2076-01-02-00000.nc
20210105_153729:index issue file: /p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BDRD/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0/20200326.BDRD_CNPECACNT_SSP585.ne30_oECv3.cori-knl.cam.h1.2077-01-02-00000.nc has index (82856.0, 83220.0) should be ((82492.0, 83220.0)), the start index is off by (364.0) days.
20210105_153729:Empty time index found in /p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BDRD/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0/20200326.BDRD_CNPECACNT_SSP585.ne30_oECv3.cori-knl.cam.h1.2101-01-02-00000.nc
20210105_153729:Result=Fail:dataset=/p/user_pub/e3sm/warehouse/E3SM/1_1_ECA/ssp585-BDRD/1deg_atm_60-30km_ocean/atmos/native/model-output/day/ens1/v0

Presently, my controlling batch script “validation.sh” poses as “Validation” and will soon take care of updating the dataset status files.

I intend to run it on a “Pile O’ Datasets” soon.

**Comment by TonyB9000** [comment]
I’ll do another run of the checker against the recently published (36 I think) BGC CTC ssp585.

____tony____
